version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - cd frontend
      - npm i
      - npm run build
  # post_build:
  #   commands:
  #     - cd dist
  #     - zip -r artifact.zip .
artifacts:
  files:
    - "**/*"
  base-directory: frontend/dist
