{
  "version": "0.2",
  "phases":
    {
      "build":
        {
          "commands":
            ["cd frontend", "npm ci", "npm run build", "npx cdk synth"],
        },
    },
  "artifacts": { "base-directory": "dist", "files": "*" },
}
